### ISSUE TITLE
Assess the utility of GML 3.3 Simple Geometries

### ISSUE THREAD

**Issue by marqh** [wmo-im/AvXML#12]
Evaluate whether the GML 3.3 simple geometries can be used to simplify the geometries used in IWXXM, in particular polygons.

ref: https://software.ecmwf.int/issues/browse/AVXML-21

Created:
    29/Sep/15 9:25 PM 

Reporter:
Aaron Braeckel

**Comment by braeckel** [comment]
This is difficult to resolve because of how AIXM defines aixm:Surface.  There are also questions about whether GML 3.3 itself is broadly implemented, and the potential benefits in terms of message sizes and complexity are relatively minor.  TT-AvXML-6 agreed to close this issue
