### ISSUE TITLE
Add AIRMET/SIGMET boundary point indexes that indicate the overlap with an FIR boundary

### ISSUE THREAD

**Issue by marqh** [wmo-im/AvXML#5]
Due to the lack of a common aeronautical database among AIRMET and SIGMET data providers, it can be the case that two reports can be issued on either side of an FIR boundary for the same meteorological condition. Until the FIR boundary issue is completely resolved it can be the case that reports issued on either side of the FIR boundary may not completely match, leaving "holes" or overlapping conditions when combined. The long term solution for this problem is to have a consistent set of aeronautical information which is used by all AIRMET/SIGMET issuers, but in the interim another solution is needed.

It was determined in TT-AvXML-4 that data providers should at least be able to indicate which points in the AIRMET/SIGMET boundary are also boundary points for the FIR boundary. With this information downstream consumers have more information by which any differences can be reconciled between FIR points described in more than one SIGMET or AIRMET that cross an FIR boundary.

ref: https://software.ecmwf.int/issues/browse/AVXML-8

Created:
    29/Sep/15 7:19 PM 

Reporter:
Aaron Braeckel

**Comment by braeckel** [comment]
Per discussion in TT-AvXML-6 this is considered to be less desirable than the intersection of geometries approach discussed in #43 and should not be utilized.
