### ISSUE TITLE
Create sample visualization/presentation alternatives to TAC

### ISSUE THREAD

**Issue by marqh** [wmo-im/AvXML#9]
Due to the fact that TAC may no longer be the only visualization of this type of information once the transition to XML has been completed, it was determined in TT-AvXML-4 that it is worthwhile to explore some of the alternative visualizations that might be used on a tablet, web site, or other user interface. For example, a tabular form, icons, etc.

It is likely that this will be useful input to ICAO for standardization and/or discussion.

ref: https://software.ecmwf.int/issues/browse/AVXML-18

Created:
    29/Sep/15 9:15 PM 

Reporter:
Aaron Braeckel

**Comment by braeckel** [comment]
TT-AvXML-6 agreed that this is a task in WG-MIE and is outside TT-AvXML's responsibility
